### ISSUE TITLE
Aui code assists has the wrong way to add code completation like A.A.AceEditor()

### ISSUE THREAD

**Issue by lilu1990** [angelozerr/tern-aui2.0.x#1]
in this project https://issues.liferay.com/secure/attachment/119162/tern-test.7z
when i do code assist in js file like :

```javascript
AUI().use('aui-base',function(B){
new A. +(Code Assist) 
})
```

it will pop out a list with many templates starts with "A." like "A.AceEditor(config)" "A.Aria(config)" etc .

then I double click one item and it added double A , when it finished code completation like this with double "A" , is it the right behavior ?

```javascript
AUI().use('aui-base',function(A){
new A.A.AceEditor(function() {

})  
})
```

https://issues.liferay.com/secure/attachment/119165/aui%20code%20assit%20completion%20has%20wrong%20way%20to%20add%20template.PNG

**Comment by angelozerr** [comment]
@lilu1990, I have fixed this problem. Here the new behaviour : 

```javascript
AUI().use('aui-base',function(B){
new A. +(Code Assist) => shows nothing because A is not an instance of YUI 
})
```

```javascript
AUI().use('aui-base',function(A){
new A. +(Code Assist) => shows AceEditor (and not A.AceEditor)
})
```

When you apply completion, it generated that (not double A) : 

```javascript
AUI().use('aui-base',function(A){
new A.AceEditor(function() {

})  
})
```

Please retry it and close this issue if it's OK. Thanks!

**Comment by lilu1990** [comment]
hi angelozerr .I'm not able to get any proposal when I do AUI().use('aui-base',function(A){
new A. +(Code Assist)
}) after I upgrade tern to http://oss.opensagres.fr/tern.repository/0.8.0-SNAPSHOT/
![nothing for code assist](https://cloud.githubusercontent.com/assets/4350803/5698841/b9ec48b6-9a52-11e4-9b62-11844cb0be54.PNG)

**Comment by angelozerr** [comment]
@lilu1990 please check you have selected :

* YUI Library 3
 * AlloyUI 2

in the Ten -> Modules of the project properties.

Your .tern-project lokks like that : 

```json
{"ide":{},"plugins":{"aui2.0.x":{},"yui3":{}},"libs":["browser","ecma5"]}
```

**Comment by lilu1990** [comment]
I have selected YUI Library 3 and AlloyUI 2 but the still no proposal  , I also tried with only select YUI or AlloyUI , but still doesn't work .

I was able to pop out A.AceEditor(config) etc when I use http://oss.opensagres.fr/tern.repository/0.7.0/ by only select AlloyUI

**Comment by angelozerr** [comment]
You use AUI and since AlloyUI 2.x, you must use YUI. try :


```javascript
YUI().use('aui-base',function(B){
new A. +(Code Assist) 
})
```

**Comment by lilu1990** [comment]
YUI works  ,It can add the code  completion rightly now

**Comment by angelozerr** [comment]
> YUI works ,It can add the code completion rightly now

Cool!

@lilu1990 can I close this issue?

@lilu1990 @gamerson do we need support AlloyUI 1.5.x which uses AUI innstead of using YUI http://alloyui.com/versions/1.5.x/ ?

**Comment by gamerson** [comment]
No, AUI 2.0.x is older version we need support for.

On Tue, Jan 13, 2015 at 4:49 PM, Angelo <notifications@github.com> wrote:

> YUI works ,It can add the code completion rightly now
>
> Cool!
>
> @lilu1990 <https://github.com/lilu1990> can I close this issue?
>
> @lilu1990 <https://github.com/lilu1990> @gamerson
> <https://github.com/gamerson> do we need support AlloyUI 1.5.x which uses
> AUI innstead of using YUI http://alloyui.com/versions/1.5.x/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern-aui2.0.x/issues/1#issuecomment-69712690>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lilu1990** [comment]
closing thanks

**Comment by angelozerr** [comment]
> No, AUI 2.0.x is older version we need support for.

Ok you mean that 1.5.x must not supported, so AUI(). should not support, is that?

@gamerson could we clarify which version of AUI we need support : 

 * http://alloyui.com/versions/1.5.x/ : it seems no (so AUI() will not work)
 * http://alloyui.com/versions/2.0.x/ : yes (it's this project)
 * http://alloyui.com/versions/2.5.x/ : do we need support it?
 * 3.0.x : it seems we need support it.
 * 4.0.x : it seems we need support it. Have you some info about that, github project?

**Comment by gamerson** [comment]
Let me check...

On Wed, Jan 14, 2015 at 4:21 PM, Angelo <notifications@github.com> wrote:

> No, AUI 2.0.x is older version we need support for.
>
> Ok you mean that 1.5.x must not supported, so AUI(). should not support,
> is that?
>
> @gamerson <https://github.com/gamerson> could we clarify which version of
> AUI we need support :
>
>    - http://alloyui.com/versions/1.5.x/ : it seems no (so AUI() will not
>    work)
>    - http://alloyui.com/versions/2.0.x/ : yes (it's this project)
>    - http://alloyui.com/versions/2.5.x/ : do we need support it?
>    - 3.0.x : it seems we need support it.
>    - 4.0.x : it seems we need support it. Have you some info about that,
>    github project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern-aui2.0.x/issues/1#issuecomment-69883248>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Here is the doc I was looking for earlier:
https://github.com/liferay/alloy-ui/wiki/Liferay-Integration

So it seems that 1.5.1x would be good to have as well, if it is easy for us
to create.

On Wed, Jan 14, 2015 at 5:09 PM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Let me check...
>
> On Wed, Jan 14, 2015 at 4:21 PM, Angelo <notifications@github.com> wrote:
>
>> No, AUI 2.0.x is older version we need support for.
>>
>> Ok you mean that 1.5.x must not supported, so AUI(). should not support,
>> is that?
>>
>> @gamerson <https://github.com/gamerson> could we clarify which version
>> of AUI we need support :
>>
>>    - http://alloyui.com/versions/1.5.x/ : it seems no (so AUI() will not
>>    work)
>>    - http://alloyui.com/versions/2.0.x/ : yes (it's this project)
>>    - http://alloyui.com/versions/2.5.x/ : do we need support it?
>>    - 3.0.x : it seems we need support it.
>>    - 4.0.x : it seems we need support it. Have you some info about that,
>>    github project?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/angelozerr/tern-aui2.0.x/issues/1#issuecomment-69883248>
>> .
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Ignore the one about AUI3.x being for portal 7.0.x  for 7.0 things are
moving to jquery based AUI

On Wed, Jan 14, 2015 at 11:59 PM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Here is the doc I was looking for earlier:
> https://github.com/liferay/alloy-ui/wiki/Liferay-Integration
>
> So it seems that 1.5.1x would be good to have as well, if it is easy for
> us to create.
>
> On Wed, Jan 14, 2015 at 5:09 PM, Greg Amerson <gregory.amerson@liferay.com
> > wrote:
>
>> Let me check...
>>
>> On Wed, Jan 14, 2015 at 4:21 PM, Angelo <notifications@github.com> wrote:
>>
>>> No, AUI 2.0.x is older version we need support for.
>>>
>>> Ok you mean that 1.5.x must not supported, so AUI(). should not support,
>>> is that?
>>>
>>> @gamerson <https://github.com/gamerson> could we clarify which version
>>> of AUI we need support :
>>>
>>>    - http://alloyui.com/versions/1.5.x/ : it seems no (so AUI() will
>>>    not work)
>>>    - http://alloyui.com/versions/2.0.x/ : yes (it's this project)
>>>    - http://alloyui.com/versions/2.5.x/ : do we need support it?
>>>    - 3.0.x : it seems we need support it.
>>>    - 4.0.x : it seems we need support it. Have you some info about
>>>    that, github project?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/angelozerr/tern-aui2.0.x/issues/1#issuecomment-69883248>
>>> .
>>>
>>
>>
>>
>> --
>> Greg Amerson
>> Liferay Developer Tools
>> Liferay, Inc. www.liferay.com
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by angelozerr** [comment]
In other words we need just 2 tern plugins : 

 * 2.0.x => sources from https://github.com/liferay/alloy-ui/tree/2.0.x
 * 1.5.x => sources from https://github.com/liferay/alloy-ui/tree/1.5.x (I don't find 1.5.1x )

For AUI4.x we need wait that AlloyUI team integrates jQuery. Do you know where I could find sources?

> So it seems that 1.5.1x would be good to have as well, if it is easy for us
to create.

I will create a new project for that this week.

**Comment by gamerson** [comment]
Right there isn't 1.5.1 that is just the latest from the tree/1.5.x

Also I woudn't put too much effort into 1.5.x that is a really old branch,
but if your tools can auto generate the tern definitions, then it would be
worth it I guess.

Regarding AUI4.x I'll get back to you on the sources for that, were they
are going.

On Thu, Jan 15, 2015 at 7:15 AM, Angelo <notifications@github.com> wrote:

> In other words we need just 2 tern plugins :
>
>    - 2.0.x => sources from https://github.com/liferay/alloy-ui/tree/2.0.x
>    - 1.5.x => sources from https://github.com/liferay/alloy-ui/tree/1.5.x
>    (I don't find 1.5.1x )
>
> For AUI4.x we need wait that AlloyUI team integrates jQuery. Do you know
> where I could find sources?
>
> So it seems that 1.5.1x would be good to have as well, if it is easy for us
> to create.
>
> I will create a new project for that this week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern-aui2.0.x/issues/1#issuecomment-70012188>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com
